const USER = {
  REGISTER: 'REGISTER',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  LOADING: 'USER_LOADING',
  LOADED: 'USER_LOADED',
  ERROR: 'USER_ERROR',
  CLEAR_ERRORS: 'CLEAR_USER_ERRORS'
};

const TABLE = {
  SET: 'SET',
  LOADING: 'TABLE_LOADING',
  LOADED: 'TABLE_LOADED',
  ERROR: 'TABLE_ERROR',
  CLEAR_ERRORS: 'CLEAR_TABLE_ERRORS'
};

const ADMIN = {
  SAVE_ITEM: 'SAVE_ITEM',
  LOADING_FORM: 'ADMIN_LOADING_FORM',
  LOADED_FORM: 'ADMIN_LOADED_FORM',
  LOADING_ITEM: 'ADMIN_LOADING_ITEM',
  LOADED_ITEM: 'ADMIN_LOADED_ITEM',
  ERROR: 'ADMIN_ERROR',
  CLEAR_ERRORS: 'CLEAR_ADMIN_ERRORS'
};


export { USER, TABLE, ADMIN };