export const GET_ERRORS = 'GET_ERRORS';
export const GET_CLEAR_ERROR = 'GET_CLEAR_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const SAVE_ITEM = 'SAVE_ITEM';
export const FIND_ITEMS = 'FIND_ITEMS';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';