const USER = {
  REGISTER: 'REGISTER',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  LOADING: 'USER_LOADING',
  LOADED: 'USER_LOADED',
  ERROR: 'USER_ERROR',
  CLEAR_ERRORS: 'CLEAR_USER_ERRORS'
};

const TARGET = {
  SET: 'SET',
  LOADING_SET: 'TARGET_LOADING_SET',
  LOADED_SET: 'TARGET_LOADED_SET',
  LOADING_CALC: 'TARGET_LOADING_CALC',
  LOADED_CALC: 'TARGET_LOADED_CALC',
  ERROR: 'TARGET_ERROR',
  CLEAR_ERRORS: 'CLEAR_TARGET_ERRORS'
};

const ADMIN = {
  SAVE_ITEM: 'SAVE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  LOADING: 'ADMIN_LOADING',
  LOADED: 'ADMIN_LOADED',
  ERROR: 'ADMIN_ERROR',
  CLEAR_ERRORS: 'CLEAR_ADMIN_ERRORS'
};


export { USER, TARGET, ADMIN };